name: ultimate_salon_owner_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.29+29

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  get: ^4.6.5
  skeletons:
    path: packages/skeletons
  image_picker: ^1.0.0
  syncfusion_flutter_calendar: ^29.1.41
  jiffy: ^6.4.3
  flutter_html: ^3.0.0-alpha.5
  connectivity_plus: ^7.0.0
  google_nav_bar: ^5.0.6
  syncfusion_flutter_charts: ^29.1.41
  flutter_otp_text_field: ^1.1.1
  webview_flutter: ^4.13.0
  country_code_picker: ^3.0.0
  url_launcher: ^6.3.1
  country_picker: ^2.0.20
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.2
  change_app_package_name: ^1.1.0
  carousel_slider: ^5.1.0
  adapty_flutter: ^3.11.0
  flutter_easyloading: ^3.0.5
  get_storage: ^2.0.3
  fluttertoast: ^8.2.1
  lottie: ^2.2.0
  intl: ^0.20.2
  geolocator: ^13.0.3
  table_calendar: ^3.0.6 
  permission_handler: ^11.3.1
  pdf: ^3.10.7             
  printing: ^5.12.0 
  pusher_channels_flutter: ^2.5.0
  app_tracking_transparency: ^2.0.5

dependency_overrides:
  webview_flutter_wkwebview: 3.23.8
  url_launcher_ios: 6.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf


